[project]
name = "quadbench"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "krishdesai7", email = "27725015+krishdesai7@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "altair>=6.2.2",
    "cupy-cuda13x>=14.1.1 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "ipykernel>=7.3.0",
    "numpy>=2.5.1",
    "numpy-quaddtype>=1.0.0",
    "polars>=1.43.2",
    "pyyaml>=6.0.3",
    "typer>=0.27.1",
]
