[project]
name = "quadbench"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "krishdesai7", email = "27725015+krishdesai7@users.noreply.github.com" }
]
requires-python = ">=3.14.7"
dependencies = [
    "altair>=6.3.0",
    "cupy-cuda13x>=14.2.0 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "ipykernel>=7.4.0",
    "jax>=0.11.2",
    "jax[cuda13]>=0.11.2 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "numpy>=2.5.3",
    "numpy-quaddtype>=1.0.0",
    "polars>=1.44.2",
    "pyyaml>=6.0.3",
    "typer>=0.27.2",
]
